language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "jruby-19mode"
  - "rbx"
env:
  - "ACTIVERECORD_VERSION=4.1.0.beta1"
  - "ACTIVERECORD_VERSION=4.0.2"
  - "ACTIVERECORD_VERSION=3.2.13"
  - "ACTIVERECORD_VERSION=3.1.12"
  - "ACTIVERECORD_VERSION=master"
matrix:
  exclude:
    - env: "ACTIVERECORD_VERSION=4.1.0.beta1"
      rvm: "1.9.2"
    - env: "ACTIVERECORD_VERSION=4.1.0.beta1"
      rvm: "1.9.3"
    - env: "ACTIVERECORD_VERSION=4.1.0.beta1"
      rvm: "jruby-19mode"
    - env: "ACTIVERECORD_VERSION=4.0.2"
      rvm: "1.9.2"
    - env: "ACTIVERECORD_VERSION=master"
      rvm: "1.9.2"
  allow_failures:
    - env: "ACTIVERECORD_VERSION=master"
